/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalonIdRouteImport } from './routes/salon.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as BookingSalonIdRouteImport } from './routes/booking.$salonId'
import { Route as BookingBarberBarberIdRouteImport } from './routes/booking.barber.$barberId'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonIdRoute = SalonIdRouteImport.update({
  id: '/salon/$id',
  path: '/salon/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatRoute,
} as any)
const BookingSalonIdRoute = BookingSalonIdRouteImport.update({
  id: '/booking/$salonId',
  path: '/booking/$salonId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBarberBarberIdRoute = BookingBarberBarberIdRouteImport.update({
  id: '/booking/barber/$barberId',
  path: '/booking/barber/$barberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/booking/$salonId': typeof BookingSalonIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/salon/$id': typeof SalonIdRoute
  '/booking/barber/$barberId': typeof BookingBarberBarberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/booking/$salonId': typeof BookingSalonIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/salon/$id': typeof SalonIdRoute
  '/booking/barber/$barberId': typeof BookingBarberBarberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/booking/$salonId': typeof BookingSalonIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/salon/$id': typeof SalonIdRoute
  '/booking/barber/$barberId': typeof BookingBarberBarberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookings'
    | '/chat'
    | '/favorites'
    | '/map'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/support'
    | '/booking/$salonId'
    | '/chat/$id'
    | '/salon/$id'
    | '/booking/barber/$barberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/chat'
    | '/favorites'
    | '/map'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/support'
    | '/booking/$salonId'
    | '/chat/$id'
    | '/salon/$id'
    | '/booking/barber/$barberId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bookings'
    | '/chat'
    | '/favorites'
    | '/map'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/support'
    | '/booking/$salonId'
    | '/chat/$id'
    | '/salon/$id'
    | '/booking/barber/$barberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  ChatRoute: typeof ChatRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  BookingSalonIdRoute: typeof BookingSalonIdRoute
  SalonIdRoute: typeof SalonIdRoute
  BookingBarberBarberIdRoute: typeof BookingBarberBarberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon/$id': {
      id: '/salon/$id'
      path: '/salon/$id'
      fullPath: '/salon/$id'
      preLoaderRoute: typeof SalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/booking/$salonId': {
      id: '/booking/$salonId'
      path: '/booking/$salonId'
      fullPath: '/booking/$salonId'
      preLoaderRoute: typeof BookingSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/barber/$barberId': {
      id: '/booking/barber/$barberId'
      path: '/booking/barber/$barberId'
      fullPath: '/booking/barber/$barberId'
      preLoaderRoute: typeof BookingBarberBarberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatIdRoute: typeof ChatIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIdRoute: ChatIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  ChatRoute: ChatRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  BookingSalonIdRoute: BookingSalonIdRoute,
  SalonIdRoute: SalonIdRoute,
  BookingBarberBarberIdRoute: BookingBarberBarberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
